### ISSUE TITLE
While GENERATING PDF giving error

### ISSUE THREAD

**Issue by infotonics-media** [FuriosoJack/TableHTMLExport#2]
`TypeError: can't assign to property "header" on "": not an object`

**Comment by FuriosoJack** [comment]
> 
> 
> `TypeError: can't assign to property "header" on "": not an object`

can you indicate the html code of the table?

**Comment by infotonics-media** [comment]
Have used some other 

> 

<table cellspacing="0" width="100%" id="example" class="display table table-bordered table-hover table-dynamic">
                    <thead>
                      <tr>
						<th class="no-sort"></th>
							
                        <th>Creation Date</th>
                        <th>Opportunity</th>
                        <th>Contact Name</th> 
                        
                        <th>Email</th>
                        <th>Phone</th>                        
                        <th>Sales Team</th>
                        <th>Options</th>     
                      </tr>
                    </thead>
                     
                    <tbody>
                      
                      					    	                      <tr id="lead_id_3">
							<td> 
								<input class="control-panel-toggle" type="checkbox" id="check-1" 
								name="check_3">
							</td>
							<td>10/23/2019</td>
	                        
	                        <td>
	                         
	                        <a href="#">TESTING NOVEMBER2</a>
	                        
	                        </td>
	                        <td>INFOTONICS MEDIA</td>
	                          
	                        
	                        <td>xxxxx@xxx.com</td>
	                        <td>xxxxxxxxxxxxxxx</td>
	                        
	                        <td>FINAL TESTING   </td>	                        
	                        <td style="width: 12%;">
	                        	
	                        	 
	                        	<a href="xxxxxxxxxx" class=" btn btn-sm btn-default dlt_sm_table"><i class="font-icon font-icon-pencil"></i></a>
	                            	                            
	                            	                         	<a href="javascript:void(0)" class="btn btn-sm btn-danger dlt_sm_table" data-toggle="modal" data-target="#modal-basic3"><i class="glyphicon glyphicon-trash"></i></a>
	                           	                         </td> 
	                      </tr>
	                      <div class="modal fade" id="modal-basic3" tabindex="-1" role="dialog" aria-hidden="true">
            				<div class="modal-dialog">
              					<div class="modal-content">
					                <div class="modal-header">
					                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icons-office-52"></i></button>
					                  <h4 class="modal-title"><strong>Confirm</strong></h4>
					                </div>
					                <div class="modal-body">
					                  Are you sure you want to delete this?<br>
					                </div>
					                <div class="modal-footer">
					                  <button type="button" class="btn btn-default btn-embossed" data-dismiss="modal">Cancel</button>
					                  <button type="button" onclick="delete_leads(3)" class="btn btn-primary btn-embossed" data-dismiss="modal">Delete</button>
					                </div>
             					 </div>
           					 </div>
        				  </div>
	                      
                    	 					  
                      
                      
                    </tbody>
                  </table>

but will share the info....
